site_name: 今夕的wiki

site_url: "https://kpole.github.io/"
site_author: "kpole"
repo_url: https://github.com/Kpole/Kpole.github.io
repo_name: "kpole/kpole.github.io"

theme:
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.top
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # primary: 'white'
    # accent: 'red'

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite: # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - tables

extra_javascript:
  - "javascripts/extra.js?v=16"
  - "javascripts/mathjax.js"
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - "javascripts/tablesort.js"

extra_css:
  - "css/extra.css"
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
  - search:
      jieba_dict: dict.txt
      jieba_dict_user: user_dict.txt

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kpole

copyright: Copyright &copy;  2022 - 2022 yaodong han

nav:
  - Home:
      - Home: "index.md"
      - 比赛记录: "record.md"
  - LeetCode:
      - 周赛:
          - 第 311 场周赛: "LeetCode/周赛/第311场周赛.md"
          - 第 310 场周赛: "LeetCode/周赛/第310场周赛.md"
          - 第 309 场周赛: "LeetCode/周赛/第309场周赛.md"
          - 第 308 场周赛: "LeetCode/周赛/第308场周赛.md"
          - 第 307 场周赛: "LeetCode/周赛/第307场周赛.md"
      - 双周赛:
          - 第 87 场双周赛: "LeetCode/双周赛/第87场双周赛.md"
          - 第 86 场双周赛: "LeetCode/双周赛/第86场双周赛.md"
      - 基础:
          - 贪心: "LeetCode/01_基础/贪心.md"
      - 数据结构:
          - 哈希:
              - 树哈希: "LeetCode/02_数据结构/哈希/树哈希.md"
          - 栈:
              - 括号匹配专题: "LeetCode/02_数据结构/栈/括号匹配专题.md"
      - 动态规划: "LeetCode/03_动态规划/index.md"
      - 字符串: "LeetCode/04_字符串/index.md"
      - 搜索: "LeetCode/05_搜索/index.md"
      - 图论: "LeetCode/06_图论/index.md"
      - 杂项: "LeetCode/07_杂项/index.md"
  - AtCoder:
      - ABC:
          - ABC 267: "AtCoder/ABC/267.md"
          - ABC 266: "AtCoder/ABC/266.md"
          - ABC 265: "AtCoder/ABC/265.md"
  - 其他:
      - 正则表达式: "other/正则表达式.md"
      - MBTI: "other/MBTI.md"
      - 正念: "other/正念.md"
