site_name: 今夕的Doc

theme:
  name: material
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.top
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - LeetCode: 
    - 周赛:
      - 第308场周赛: 'LeetCode/周赛/第308场周赛.md' 
      - 第307场周赛: 'LeetCode/周赛/第307场周赛.md'
  - About: 'about.md'
