site_name: 今夕的Doc

site_url: 'https://kpole.github.io/'
site_author: 'kpole'
repo_url: https://github.com/Kpole/Kpole.github.io
repo_name: 'kpole/kpole.github.io'

theme:
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.top
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
  - search:
      jieba_dict: dict.txt 
      jieba_dict_user: user_dict.txt
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kpole

copyright: Copyright &copy;  2022 - 2022 yaodong han



nav:
  - Home: 'index.md'
  - LeetCode: 
    - 周赛:
      - 第308场周赛: 'LeetCode/周赛/第308场周赛.md' 
      - 第307场周赛: 'LeetCode/周赛/第307场周赛.md'
  - AtCoder:
    - ABC: 
      - ABC 266: 'AtCoder/ABC/266.md'
      - ABC 265: 'AtCoder/ABC/265.md'
  - About: 'about.md'

